feat(SocketClient): The three lines above should be declared outside …
generalsoftwareinc/DeribitServiceClient pull request #49
Opened 2023-02-16 22:56 UTC by gsi-juandavid

…the method as global states to avoid generating garbage on the heap

2023-02-16 23:00 UTC, gsi-yoancme requested changes

2023-02-16 23:00 UTC, gsi-yoancme commented on src/ServiceClient/Implements/SocketClient/DeribitSocketClient.cs
> -        var receiveValidStates = new[] { WebSocketState.Open, WebSocketState.CloseSent };
the string builder will need to start clear in each call.

2023-02-16 23:00 UTC, gsi-yoancme commented on src/ServiceClient/Implements/SocketClient/DeribitSocketClient.cs
> -        var receiveValidStates = new[] { WebSocketState.Open, WebSocketState.CloseSent };
stringBuilder.Clear()

2023-02-16 23:01 UTC, gsi-yoancme approved these changes

2023-02-17 13:04 UTC, gsi-robertogarcia approved these changes

2023-02-17 14:24 UTC, merged